name: Build/Test

on:
  pull_request:
    branches: [main]

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Install GDAL Dev libs
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y libgdal-dev
      - name: Run Tests
        run: |
          go test -short ./... -coverprofile=coverage.out -covermode=atomic
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage.out
